CREATE TABLE Sheet1(/*Aggregation_Function VARCHAR(10));
INSERT INTO Sheet1 (/*Aggregation_Function) VALUES 
('Aggregation operations functions on a set of values and returns single value.'),
('Used in group by classes'),
('1.Sum- Submission of the set of values.'),
('2. Avg - to calculate average'),
('3. Count - to count the records/no of rows'),
('4.  Min/max - to find the minimum and maximum values.*/'),
('mysql> select * from product;'),
('+------------+--------------+------------+---------------+---------------+-------+'),
('| product_id | product_name | category   | orignal_price | selling_price | stock |'),
('+------------+--------------+------------+---------------+---------------+-------+'),
('| P101       | Table        | Furniture  |           100 |            80 |    23 |'),
('| P102       | Chair        | Furniture  |           230 |           180 |    23 |'),
('| P103       | Laptop       | Electronic |         34000 |         30000 |     3 |'),
('| P104       | mobile       | Electronic |         32220 |         12210 |     3 |'),
('+------------+--------------+------------+---------------+---------------+-------+'),
('4 rows in set (0.001 sec)'),
(' #using SUM command '),
('mysql> select sum(selling_price) from product;'),
('+--------------------+'),
('| sum(selling_price) |'),
('+--------------------+'),
('|              42470 |'),
('+--------------------+'),
('1 row in set (0.004 sec)'),
(' #using AVG command '),
('mysql> select avg(selling_price) from product;'),
('+--------------------+'),
('| avg(selling_price) |'),
('+--------------------+'),
('|         10617.5000 |'),
('+--------------------+'),
('1 row in set (0.004 sec)'),
(' #using count command to find the numbers of total rows'),
('mysql> select count(*) from product;'),
('+----------+'),
('| count(*) |'),
('+----------+'),
('|        4 |'),
('+----------+'),
('1 row in set (0.006 sec)'),
(' #using max command '),
('mysql> select max(stock) from product;'),
('+------------+'),
('| max(stock) |'),
('+------------+'),
('|         23 |'),
('+------------+'),
('1 row in set (0.004 sec)'),
(' #using min command '),
('mysql> select min(stock) from product;'),
('+------------+'),
('| min(stock) |'),
('+------------+'),
('|          3 |'),
('+------------+'),
('1 row in set (0.000 sec)'),
('#ORDER BY is a CLAUSE to sort your data either in ascending order or descending order '),
('#For ascending '),
('mysql> select * from product order by stock;'),
('+------------+--------------+------------+---------------+---------------+-------+'),
('| product_id | product_name | category   | orignal_price | selling_price | stock |'),
('+------------+--------------+------------+---------------+---------------+-------+'),
('| P103       | Laptop       | Electronic |         34000 |         30000 |     3 |'),
('| P104       | mobile       | Electronic |         32220 |         12210 |     3 |'),
('| P101       | Table        | Furniture  |           100 |            80 |    23 |'),
('| P102       | Chair        | Furniture  |           230 |           180 |    23 |'),
('+------------+--------------+------------+---------------+---------------+-------+'),
(' '),
('#For descending use DESC '),
('mysql> select * from product order by stock desc;'),
('+------------+--------------+------------+---------------+---------------+-------+'),
('| product_id | product_name | category   | orignal_price | selling_price | stock |'),
('+------------+--------------+------------+---------------+---------------+-------+'),
('| P101       | Table        | Furniture  |           100 |            80 |    23 |'),
('| P102       | Chair        | Furniture  |           230 |           180 |    23 |'),
('| P103       | Laptop       | Electronic |         34000 |         30000 |     3 |'),
('| P104       | mobile       | Electronic |         32220 |         12210 |     3 |'),
('+------------+--------------+------------+---------------+---------------+-------+'),
('4 rows in set (0.001 sec)'),
('#For selective rows data;'),
('mysql> select * from product order by stock desc limit 3;'),
('+------------+--------------+------------+---------------+---------------+-------+'),
('| product_id | product_name | category   | orignal_price | selling_price | stock |'),
('+------------+--------------+------------+---------------+---------------+-------+'),
('| P101       | Table        | Furniture  |           100 |            80 |    23 |'),
('| P102       | Chair        | Furniture  |           230 |           180 |    23 |'),
('| P103       | Laptop       | Electronic |         34000 |         30000 |     3 |'),
('+------------+--------------+------------+---------------+---------------+-------+'),
('3 rows in set (0.002 sec)'),
('/*Questions'),
('Count total no of employee as of each department '),
('mysql> select department_name, count(*) as Total_employees from employee group by department_name;'),
('Count total salary by department '),
('mysql> select department_name, sum(salary) as total_salary from employee group by department_name;'),
('Count avg salary by department '),
('mysql> select department_name, avg(salary) as average_salary from employee group by department_name; */'),
('mysql> select department_name, salary, count(*) from employee group by department_name, salary;'),
('+-----------------+--------+----------+'),
('| department_name | salary | count(*) |'),
('+-----------------+--------+----------+'),
('| HR              |  40000 |        1 |'),
('| IT              |   6000 |        1 |'),
('| IT              |   7000 |        1 |'),
('| HR              |  45000 |        1 |'),
('| Finance         |  50000 |        1 |'),
('+-----------------+--------+----------+'),
('/*Having clause is use to to filter after using group by clause'),
('Jiska count >1 hai usda data fetch karna hai (count)'),
('mysql> select department_name, count(*) as total_employee from employee group by department_name having count(*) >1;'),
('Return the department with total salary >8000 (sum)'),
('mysql> select department_name, sum(salary) as total_salary from employee group by department_name having sum(salary)>8000;'),
('Return the department with average salary >5000 (average)'),
('mysql> select department_name, avg(salary) as avergae_salary from employee group by department_name having avg(salary)>5000; */'),
('#Having clause always work In aggregation function');