CREATE TABLE Sheet1(mysql>_create_database_joins; VARCHAR(10));
INSERT INTO Sheet1 (mysql>_create_database_joins;) VALUES 
('Query OK, 1 row affected (0.056 sec)'),
('mysql> use joins;'),
('Database changed'),
('mysql> create table department (dept_id varchar(10) primary key not null, dept_name varchar(30) not null);'),
('Query OK, 0 rows affected (0.049 sec)'),
('mysql> desc department;'),
('+-----------+-------------+------+-----+---------+-------+'),
('| Field     | Type        | Null | Key | Default | Extra |'),
('+-----------+-------------+------+-----+---------+-------+'),
('| dept_id   | varchar(10) | NO   | PRI | NULL    |       |'),
('| dept_name | varchar(30) | NO   |     | NULL    |       |'),
('+-----------+-------------+------+-----+---------+-------+'),
('2 rows in set (0.013 sec)'),
('mysql> insert into department values (1,'HR'),(2,'IT'),(3,'Finance'),(4,'Marketing');'),
('Query OK, 4 rows affected (0.017 sec)'),
('Records: 4  Duplicates: 0  Warnings: 0'),
('mysql> select * from department;'),
('+---------+-----------+'),
('| dept_id | dept_name |'),
('+---------+-----------+'),
('| 1       | HR        |'),
('| 2       | IT        |'),
('| 3       | Finance   |'),
('| 4       | Marketing |'),
('+---------+-----------+'),
('4 rows in set (0.001 sec)'),
('mysql> DESCRIBE department;'),
('+-----------+-------------+------+-----+---------+-------+'),
('| Field     | Type        | Null | Key | Default | Extra |'),
('+-----------+-------------+------+-----+---------+-------+'),
('| dept_id   | varchar(10) | NO   | PRI | NULL    |       |'),
('| dept_name | varchar(30) | NO   |     | NULL    |       |'),
('+-----------+-------------+------+-----+---------+-------+'),
('2 rows in set (0.030 sec)'),
('mysql> create table employee(emp_id int primary key not null, emp_name varchar(30) not null,dept_id varchar(10), foreign key(dept_id) references department(dept_id) );'),
('Query OK, 0 rows affected (0.047 sec)'),
('mysql> insert into employee values (1,'Mannan',1),(2,'Ayesha',2),(3,'Khan',1),(4,'Ansari',3),(5,'Salman', null );'),
('Query OK, 5 rows affected (0.006 sec)'),
('Records: 5  Duplicates: 0  Warnings: 0'),
('mysql> select * from employee;'),
('+--------+----------+---------+'),
('| emp_id | emp_name | dept_id |'),
('+--------+----------+---------+'),
('|      1 | Mannan   | 1       |'),
('|      2 | Ayesha   | 2       |'),
('|      3 | Khan     | 1       |'),
('|      4 | Ansari   | 3       |'),
('|      5 | Salman   | NULL    |'),
('+--------+----------+---------+'),
('5 rows in set (0.002 sec)'),
('mysql> select emp_name,dept_name from employee inner join department on employee.dept_id=department.dept_id;'),
('+----------+-----------+'),
('| emp_name | dept_name |'),
('+----------+-----------+'),
('| Mannan   | HR        |'),
('| Khan     | HR        |'),
('| Ayesha   | IT        |'),
('| Ansari   | Finance   |'),
('+----------+-----------+'),
('4 rows in set (0.006 sec)'),
('mysql> select emp_name,dept_name from employee left join department on employee.dept_id=department.dept_id;'),
('+----------+-----------+'),
('| emp_name | dept_name |'),
('+----------+-----------+'),
('| Mannan   | HR        |'),
('| Ayesha   | IT        |'),
('| Khan     | HR        |'),
('| Ansari   | Finance   |'),
('| Salman   | NULL      |'),
('+----------+-----------+'),
('5 rows in set (0.007 sec)'),
('mysql> select emp_name,dept_name from employee right join department on employee.dept_id=department.dept_id;'),
('+----------+-----------+'),
('| emp_name | dept_name |'),
('+----------+-----------+'),
('| Mannan   | HR        |'),
('| Khan     | HR        |'),
('| Ayesha   | IT        |'),
('| Ansari   | Finance   |'),
('| NULL     | Marketing |'),
('+----------+-----------+'),
('5 rows in set (0.007 sec)'),
('mysql> select emp_name,dept_name from employee full join department ;'),
('+----------+-----------+'),
('| emp_name | dept_name |'),
('+----------+-----------+'),
('| Mannan   | Marketing |'),
('| Mannan   | Finance   |'),
('| Mannan   | IT        |'),
('| Mannan   | HR        |'),
('| Ayesha   | Marketing |'),
('| Ayesha   | Finance   |'),
('| Ayesha   | IT        |'),
('| Ayesha   | HR        |'),
('| Khan     | Marketing |'),
('| Khan     | Finance   |'),
('| Khan     | IT        |'),
('| Khan     | HR        |'),
('| Ansari   | Marketing |'),
('| Ansari   | Finance   |'),
('| Ansari   | IT        |'),
('| Ansari   | HR        |'),
('| Salman   | Marketing |'),
('| Salman   | Finance   |'),
('| Salman   | IT        |'),
('| Salman   | HR        |'),
('+----------+-----------+'),
('20 rows in set, 1 warning (0.054 sec)'),
('mysql> select emp_name,dept_name from employee cross join department ;'),
('+----------+-----------+'),
('| emp_name | dept_name |'),
('+----------+-----------+'),
('| Mannan   | Marketing |'),
('| Mannan   | Finance   |'),
('| Mannan   | IT        |'),
('| Mannan   | HR        |'),
('| Ayesha   | Marketing |'),
('| Ayesha   | Finance   |'),
('| Ayesha   | IT        |'),
('| Ayesha   | HR        |'),
('| Khan     | Marketing |'),
('| Khan     | Finance   |'),
('| Khan     | IT        |'),
('| Khan     | HR        |'),
('| Ansari   | Marketing |'),
('| Ansari   | Finance   |'),
('| Ansari   | IT        |'),
('| Ansari   | HR        |'),
('| Salman   | Marketing |'),
('| Salman   | Finance   |'),
('| Salman   | IT        |'),
('| Salman   | HR        |'),
('+----------+-----------+'),
('20 rows in set (0.003 sec)'),
('mysql> select emp_name,dept_name from employee self join department ;'),
('+----------+-----------+'),
('| emp_name | dept_name |'),
('+----------+-----------+'),
('| Mannan   | Marketing |'),
('| Mannan   | Finance   |'),
('| Mannan   | IT        |'),
('| Mannan   | HR        |'),
('| Ayesha   | Marketing |'),
('| Ayesha   | Finance   |'),
('| Ayesha   | IT        |'),
('| Ayesha   | HR        |'),
('| Khan     | Marketing |'),
('| Khan     | Finance   |'),
('| Khan     | IT        |'),
('| Khan     | HR        |'),
('| Ansari   | Marketing |'),
('| Ansari   | Finance   |'),
('| Ansari   | IT        |'),
('| Ansari   | HR        |'),
('| Salman   | Marketing |'),
('| Salman   | Finance   |'),
('| Salman   | IT        |'),
('| Salman   | HR        |'),
('+----------+-----------+'),
('20 rows in set (0.002 sec)'),
('mysql> create database store_procedure_example;'),
('Query OK, 1 row affected (0.019 sec)'),
('mysql> use store_procedure_example;'),
('Database changed'),
('mysql> create table employee(id int primary key not null, name varchar(20) not null,dept varchar(20) not null, salary int not null); '),
('Query OK, 0 rows affected (0.046 sec)'),
('mysql> insert into employee value (1,'Mannan','HR',10000);'),
('Query OK, 1 row affected (0.010 sec)'),
('mysql> select * from employee;'),
('+----+--------+------+--------+'),
('| id | name   | dept | salary |'),
('+----+--------+------+--------+'),
('|  1 | Mannan | HR   |  10000 |'),
('+----+--------+------+--------+'),
('1 row in set (0.001 sec)'),
('mysql> DELIMITER //'),
('mysql> '),
('mysql> CREATE PROCEDURE GetEmployees()'),
('    -> BEGIN'),
('    ->     SELECT * FROM Employee;'),
('    -> END //'),
('Query OK, 0 rows affected (0.012 sec)'),
('mysql> '),
('mysql> DELIMITER ;'),
('mysql> call GetEmployees();'),
('+----+--------+------+--------+'),
('| id | name   | dept | salary |'),
('+----+--------+------+--------+'),
('|  1 | Mannan | HR   |  10000 |'),
('+----+--------+------+--------+'),
('1 row in set (0.007 sec)'),
('Query OK, 0 rows affected (0.008 sec)'),
('mysql> call GetEmployees;'),
('+----+--------+------+--------+'),
('| id | name   | dept | salary |'),
('+----+--------+------+--------+'),
('|  1 | Mannan | HR   |  10000 |'),
('+----+--------+------+--------+'),
('1 row in set (0.001 sec)'),
('Query OK, 0 rows affected (0.001 sec)'),
('mysql> '),
('mysql>'),
('mysql> CREATE PROCEDURE GetEmployeeByDept4(IN name VARCHAR(50))'),
('    -> BEGIN'),
('    ->     SELECT * '),
('    ->     FROM Employee'),
('    ->     WHERE dept = name;'),
('    -> END //'),
('Query OK, 0 rows affected (0.008 sec)'),
('mysql> '),
('mysql> DELIMITER ;'),
('mysql> call GetEmployeeByDept4('HR');'),
('+----+--------+------+--------+'),
('| id | name   | dept | salary |'),
('+----+--------+------+--------+'),
('|  1 | Mannan | HR   |  10000 |'),
('+----+--------+------+--------+'),
('1 row in set (0.003 sec)'),
('Query OK, 0 rows affected (0.003 sec)'),
('mysql> call GetEmployeeByDept4('IT');'),
('Empty set (0.001 sec)'),
('Query OK, 0 rows affected (0.001 sec)'),
('mysql> DELIMITER //'),
('mysql> '),
('mysql> CREATE PROCEDURE AddEmployee('),
('    ->     IN  id INT,'),
('    ->     IN name VARCHAR(50),'),
('    ->     IN dept VARCHAR(50),'),
('    ->     IN salary INT'),
('    -> )'),
('    -> BEGIN'),
('    ->     INSERT INTO Employee(id, name, dept, salary)'),
('    ->     VALUES(id, name, dept, salary);'),
('    -> END //'),
('Query OK, 0 rows affected (0.005 sec)'),
('mysql> '),
('mysql> DELIMITER ;'),
('mysql> call AddEmployee(2,'Khan','IT',12000);'),
('Query OK, 1 row affected (0.005 sec)'),
('mysql> select * from employee;'),
('+----+--------+------+--------+'),
('| id | name   | dept | salary |'),
('+----+--------+------+--------+'),
('|  1 | Mannan | HR   |  10000 |'),
('|  2 | Khan   | IT   |  12000 |'),
('+----+--------+------+--------+'),
('2 rows in set (0.001 sec)'),
('mysql> DELIMITER //'),
('mysql> '),
('mysql> CREATE PROCEDURE GetEmployeeCount(OUT total INT)'),
('    -> BEGIN'),
('    ->     SELECT COUNT(*) INTO total'),
('    ->     FROM Employee;'),
('    -> END //'),
('Query OK, 0 rows affected (0.004 sec)'),
('mysql> '),
('mysql> DELIMITER ;'),
('mysql> '),
('mysql> CALL GetEmployeeCount(@total);'),
('Query OK, 1 row affected (0.006 sec)'),
('mysql> SELECT @total;'),
('+--------+'),
('| @total |'),
('+--------+'),
('|      2 |'),
('+--------+'),
('1 row in set (0.000 sec)'),
('mysql> '),
('mysql> ');