CREATE TABLE Sheet1(To_update_phone_number VARCHAR(10));
INSERT INTO Sheet1 (To_update_phone_number) VALUES 
('mysql> update customer set phone_number = '7208226998' where customer_id = 'C101';'),
('Query OK, 1 row affected (0.02 sec)'),
('Rows matched: 1  Changed: 1  Warnings: 0'),
('mysql> select * from customer;'),
('+-------------+---------------+--------+-------------------+----------------+--------------+---------+------+--------+'),
('| customer_id | customer_name | city   | email             | address        | phone_number | pincode | bill | state  |'),
('+-------------+---------------+--------+-------------------+----------------+--------------+---------+------+--------+'),
('| C101        | Ayesha        | Thane  | ayesha@gmail.com  | Almas          | 7208226998   | 400612  |    0 |        |'),
('| C102        | Ariba         | Mumbra | ariba@gmail.com   | Zoha Apartment | 2345678906   | 400612  |    0 |        |'),
('| C103        | Arshiya       | thane  | arshiya@gmail.com | grace          | 937261234    | 10654   |   10 | mumbai |'),
('+-------------+---------------+--------+-------------------+----------------+--------------+---------+------+--------+'),
('3 rows in set (0.00 sec)'),
('#To check patterns with wild card operator %'),
('mysql> select * from customer;'),
('+-------------+---------------+--------+-------------------+----------------+--------------+---------+------+--------+'),
('| customer_id | customer_name | city   | email             | address        | phone_number | pincode | bill | state  |'),
('+-------------+---------------+--------+-------------------+----------------+--------------+---------+------+--------+'),
('| C101        | Ayesha        | Thane  | ayesha@gmail.com  | Almas          | 7208226998   | 400612  |    0 |        |'),
('| C102        | Ariba         | Mumbra | ariba@gmail.com   | Zoha Apartment | 2345678906   | 400612  |    0 |        |'),
('| C103        | Arshiya       | thane  | arshiya@gmail.com | grace          | 937261234    | 10654   |   10 | mumbai |'),
('+-------------+---------------+--------+-------------------+----------------+--------------+---------+------+--------+'),
('3 rows in set (0.00 sec)'),
('#To check where name end with “ya"'),
('mysql> select * from customer where customer_name like '%ya';'),
('+-------------+---------------+-------+-------------------+---------+--------------+---------+------+--------+'),
('| customer_id | customer_name | city  | email             | address | phone_number | pincode | bill | state  |'),
('+-------------+---------------+-------+-------------------+---------+--------------+---------+------+--------+'),
('| C103        | Arshiya       | thane | arshiya@gmail.com | grace   | 937261234    | 10654   |   10 | mumbai |'),
('+-------------+---------------+-------+-------------------+---------+--------------+---------+------+--------+'),
('1 row in set (0.00 sec)'),
('#To check where name has ‘yes’ in between'),
('mysql> select * from customer where customer_name like '%yes%';'),
('+-------------+---------------+-------+------------------+---------+--------------+---------+------+-------+'),
('| customer_id | customer_name | city  | email            | address | phone_number | pincode | bill | state |'),
('+-------------+---------------+-------+------------------+---------+--------------+---------+------+-------+'),
('| C101        | Ayesha        | Thane | ayesha@gmail.com | Almas   | 7208226998   | 400612  |    0 |       |'),
('+-------------+---------------+-------+------------------+---------+--------------+---------+------+-------+'),
('1 row in set (0.00 sec)'),
('#To check name start with ‘Ar''),
('mysql> select * from customer where customer_name like 'Ar%';'),
('+-------------+---------------+--------+-------------------+----------------+--------------+---------+------+--------+'),
('| customer_id | customer_name | city   | email             | address        | phone_number | pincode | bill | state  |'),
('+-------------+---------------+--------+-------------------+----------------+--------------+---------+------+--------+'),
('| C102        | Ariba         | Mumbra | ariba@gmail.com   | Zoha Apartment | 2345678906   | 400612  |    0 |        |'),
('| C103        | Arshiya       | thane  | arshiya@gmail.com | grace          | 937261234    | 10654   |   10 | mumbai |'),
('+-------------+---------------+--------+-------------------+----------------+--------------+---------+------+--------+'),
('2 rows in set (0.00 sec)'),
('#To find character with wild card character underscore(_)'),
('mysql> select * from customer where customer_name like 'A____';'),
('+-------------+---------------+--------+-----------------+----------------+--------------+---------+------+-------+'),
('| customer_id | customer_name | city   | email           | address        | phone_number | pincode | bill | state |'),
('+-------------+---------------+--------+-----------------+----------------+--------------+---------+------+-------+'),
('| C102        | Ariba         | Mumbra | ariba@gmail.com | Zoha Apartment | 2345678906   | 400612  |    0 |       |'),
('+-------------+---------------+--------+-----------------+----------------+--------------+---------+------+-------+'),
('1 row in set (0.00 sec)'),
('#To retreive only first 3 records limit keyword used'),
('mysql> select * from customer limit 3;'),
('+-------------+---------------+--------+-------------------+----------------+--------------+---------+------+--------+'),
('| customer_id | customer_name | city   | email             | address        | phone_number | pincode | bill | state  |'),
('+-------------+---------------+--------+-------------------+----------------+--------------+---------+------+--------+'),
('| C101        | Ayesha        | Thane  | ayesha@gmail.com  | Almas          | 7208226998   | 400612  |    0 |        |'),
('| C102        | Ariba         | Mumbra | ariba@gmail.com   | Zoha Apartment | 2345678906   | 400612  |    0 |        |'),
('| C103        | Arshiya       | thane  | arshiya@gmail.com | grace          | 937261234    | 10654   |   10 | mumbai |'),
('+-------------+---------------+--------+-------------------+----------------+--------------+---------+------+--------+'),
('3 rows in set (0.00 sec)'),
('#Unique records are shown using distinct keyword'),
('mysql> select distinct city from customer;'),
('+--------+'),
('| city   |'),
('+--------+'),
('| Thane  |'),
('| Mumbra |'),
('| diva   |'),
('| kalyan |'),
('+————+'),
('#Logical operators'),
('#Bill less than 10'),
('mysql> select * from customer where bill<10;'),
('+-------------+---------------+--------+------------------+----------------+--------------+---------+------+-------+'),
('| customer_id | customer_name | city   | email            | address        | phone_number | pincode | bill | state |'),
('+-------------+---------------+--------+------------------+----------------+--------------+---------+------+-------+'),
('| C101        | Ayesha        | Thane  | ayesha@gmail.com | Almas          | 7208226998   | 400612  |    0 |       |'),
('| C102        | Ariba         | Mumbra | ariba@gmail.com  | Zoha Apartment | 2345678906   | 400612  |    0 |       |'),
('+-------------+---------------+--------+------------------+----------------+--------------+---------+------+-------+'),
('2 rows in set (0.01 sec)'),
('#Bill greater than 10'),
('mysql> select * from customer where bill>10;'),
('+-------------+---------------+------+-------------------+---------+--------------+---------+------+--------+'),
('| customer_id | customer_name | city | email             | address | phone_number | pincode | bill | state  |'),
('+-------------+---------------+------+-------------------+---------+--------------+---------+------+--------+'),
('| C106        | Arshiya       | diva | arshiya@gmail.com | grace   | 937261234    | 10654   |   11 | mumbai |'),
('+-------------+---------------+------+-------------------+---------+--------------+---------+------+--------+'),
('1 row in set (0.00 sec)'),
('#Less than equal to'),
('mysql> select * from customer where bill<=10;'),
('+-------------+---------------+--------+-------------------+----------------+--------------+---------+------+--------+'),
('| customer_id | customer_name | city   | email             | address        | phone_number | pincode | bill | state  |'),
('+-------------+---------------+--------+-------------------+----------------+--------------+---------+------+--------+'),
('| C101        | Ayesha        | Thane  | ayesha@gmail.com  | Almas          | 7208226998   | 400612  |    0 |        |'),
('| C102        | Ariba         | Mumbra | ariba@gmail.com   | Zoha Apartment | 2345678906   | 400612  |    0 |        |'),
('| C103        | Arshiya       | thane  | arshiya@gmail.com | grace          | 937261234    | 10654   |   10 | mumbai |'),
('| C104        | Arshiya       | diva   | arshiya@gmail.com | grace          | 937261234    | 10654   |   10 | mumbai |'),
('| C105        | mannan        | kalyan | mannan@gmail.com  | universe       | 1234567890   | 400612  |   10 | goa    |'),
('+-------------+---------------+--------+-------------------+----------------+--------------+---------+------+--------+'),
('5 rows in set (0.00 sec)'),
('#And operator '),
('mysql> select * from customer where customer_name ='Ayesha' and bill= 10;'),
('Empty set (0.00 sec)'),
('#Or operator '),
('mysql> select * from customer where customer_name ='Ayesha' or bill= 10;'),
('+-------------+---------------+--------+-------------------+----------+--------------+---------+------+--------+'),
('| customer_id | customer_name | city   | email             | address  | phone_number | pincode | bill | state  |'),
('+-------------+---------------+--------+-------------------+----------+--------------+---------+------+--------+'),
('| C101        | Ayesha        | Thane  | ayesha@gmail.com  | Almas    | 7208226998   | 400612  |    0 |        |'),
('| C103        | Arshiya       | thane  | arshiya@gmail.com | grace    | 937261234    | 10654   |   10 | mumbai |'),
('| C104        | Arshiya       | diva   | arshiya@gmail.com | grace    | 937261234    | 10654   |   10 | mumbai |'),
('| C105        | mannan        | kalyan | mannan@gmail.com  | universe | 1234567890   | 400612  |   10 | goa    |'),
('+-------------+---------------+--------+-------------------+----------+--------------+---------+------+--------+'),
('4 rows in set (0.00 sec)'),
('#Between operator to specify range'),
('mysql> Select * from customer where customer_id between 'C101' and 'C104';'),
('+-------------+---------------+--------+-------------------+----------------+--------------+---------+------+--------+'),
('| customer_id | customer_name | city   | email             | address        | phone_number | pincode | bill | state  |'),
('+-------------+---------------+--------+-------------------+----------------+--------------+---------+------+--------+'),
('| C101        | Ayesha        | Thane  | ayesha@gmail.com  | Almas          | 7208226998   | 400612  |    0 |        |'),
('| C102        | Ariba         | Mumbra | ariba@gmail.com   | Zoha Apartment | 2345678906   | 400612  |    0 |        |'),
('| C103        | Arshiya       | thane  | arshiya@gmail.com | grace          | 937261234    | 10654   |   10 | mumbai |'),
('| C104        | Arshiya       | diva   | arshiya@gmail.com | grace          | 937261234    | 10654   |   10 | mumbai |'),
('+-------------+---------------+--------+-------------------+----------------+--------------+---------+------+————+'),
('#Not between operator'),
('mysql> Select * from customer where customer_id not between 'C101' and 'C104';'),
('+-------------+---------------+--------+-------------------+----------+--------------+---------+------+--------+'),
('| customer_id | customer_name | city   | email             | address  | phone_number | pincode | bill | state  |'),
('+-------------+---------------+--------+-------------------+----------+--------------+---------+------+--------+'),
('| C105        | mannan        | kalyan | mannan@gmail.com  | universe | 1234567890   | 400612  |   10 | goa    |'),
('| C106        | Arshiya       | diva   | arshiya@gmail.com | grace    | 937261234    | 10654   |   11 | mumbai |'),
('+-------------+---------------+--------+-------------------+----------+--------------+---------+------+————+'),
('#Select customer id whose id are C101,C104,C105 (non squential)'),
('mysql> select * from customer where customer_id in ('C101','C104','C105');'),
('+-------------+---------------+--------+-------------------+----------+--------------+---------+------+--------+'),
('| customer_id | customer_name | city   | email             | address  | phone_number | pincode | bill | state  |'),
('+-------------+---------------+--------+-------------------+----------+--------------+---------+------+--------+'),
('| C101        | Ayesha        | Thane  | ayesha@gmail.com  | Almas    | 7208226998   | 400612  |    0 |        |'),
('| C104        | Arshiya       | diva   | arshiya@gmail.com | grace    | 937261234    | 10654   |   10 | mumbai |'),
('| C105        | mannan        | kalyan | mannan@gmail.com  | universe | 1234567890   | 400612  |   10 | goa    |'),
('+-------------+---------------+--------+-------------------+----------+--------------+---------+------+--------+'),
('3 rows in set (0.00 sec)'),
('#Select customer id whose id are NOT C101,C104,C105'),
('mysql> select * from customer where customer_id not in ('C101','C104','C105');'),
('+-------------+---------------+--------+-------------------+----------------+--------------+---------+------+--------+'),
('| customer_id | customer_name | city   | email             | address        | phone_number | pincode | bill | state  |'),
('+-------------+---------------+--------+-------------------+----------------+--------------+---------+------+--------+'),
('| C102        | Ariba         | Mumbra | ariba@gmail.com   | Zoha Apartment | 2345678906   | 400612  |    0 |        |'),
('| C103        | Arshiya       | thane  | arshiya@gmail.com | grace          | 937261234    | 10654   |   10 | mumbai |'),
('| C106        | Arshiya       | diva   | arshiya@gmail.com | grace          | 937261234    | 10654   |   11 | mumbai |'),
('+-------------+---------------+--------+-------------------+----------------+--------------+---------+------+--------+'),
('3 rows in set (0.00 sec)'),
('#Retreive email which are null'),
('mysql> select * from customer where email is null;'),
('Empty set (0.00 sec)'),
('#Retreive email which are not null'),
('mysql> select * from customer where email is not null;'),
('+-------------+---------------+--------+-------------------+----------------+--------------+---------+------+--------+'),
('| customer_id | customer_name | city   | email             | address        | phone_number | pincode | bill | state  |'),
('+-------------+---------------+--------+-------------------+----------------+--------------+---------+------+--------+'),
('| C101        | Ayesha        | Thane  | ayesha@gmail.com  | Almas          | 7208226998   | 400612  |    0 |        |'),
('| C102        | Ariba         | Mumbra | ariba@gmail.com   | Zoha Apartment | 2345678906   | 400612  |    0 |        |'),
('| C103        | Arshiya       | thane  | arshiya@gmail.com | grace          | 937261234    | 10654   |   10 | mumbai |'),
('| C104        | Arshiya       | diva   | arshiya@gmail.com | grace          | 937261234    | 10654   |   10 | mumbai |'),
('| C105        | mannan        | kalyan | mannan@gmail.com  | universe       | 1234567890   | 400612  |   10 | goa    |'),
('| C106        | Arshiya       | diva   | arshiya@gmail.com | grace          | 937261234    | 10654   |   11 | mumbai |'),
('+-------------+---------------+--------+-------------------+----------------+--------------+---------+------+--------+');