CREATE TABLE Sheet1(Column_1 VARCHAR(10));
INSERT INTO Sheet1 (Column_1) VALUES 
('mysql> -- Create a table with named Feedback with attributes:  FeedbackID (Primary Key) , StudentID (Foreign key) , Date, InstructorName, Feedback'),
('Query OK, 0 rows affected (0.001 sec)'),
('mysql> create database studentmanagementsystem ;'),
('Query OK, 1 row affected (0.038 sec)'),
('mysql> show databases ;'),
('+-------------------------+'),
('| Database                |'),
('+-------------------------+'),
('| ecommerce               |'),
('| information_schema      |'),
('| mydb                    |'),
('| mysql                   |'),
('| performance_schema      |'),
('| studentmanagementsystem |'),
('| sys                     |'),
('+-------------------------+'),
('7 rows in set (0.024 sec)'),
('mysql> use studentmanagementsystem ;'),
('Database changed'),
('mysql> create table student (student_id varchar(5) primary key not null, name varchar(20) not null, age int not null, phone_number varchar(10) not null );'),
('Query OK, 0 rows affected (0.052 sec)'),
('mysql> desc student'),
('    -> ;'),
('+--------------+-------------+------+-----+---------+-------+'),
('| Field        | Type        | Null | Key | Default | Extra |'),
('+--------------+-------------+------+-----+---------+-------+'),
('| student_id   | varchar(5)  | NO   | PRI | NULL    |       |'),
('| name         | varchar(20) | NO   |     | NULL    |       |'),
('| age          | int         | NO   |     | NULL    |       |'),
('| phone_number | varchar(10) | NO   |     | NULL    |       |'),
('+--------------+-------------+------+-----+---------+-------+'),
('4 rows in set (0.014 sec)'),
('mysql> create table Feedbacks (FeedbackID varchar(5) primary key not null, student_id varchar(5) not null, Date date not null, InstructorName varchar(20) not null, Feedback varchar(100) not null, foreign key (student_id) references student (student_id) );'),
('Query OK, 0 rows affected (0.022 sec)'),
('mysql> desc Feedbacks'),
('    -> ;'),
('+----------------+--------------+------+-----+---------+-------+'),
('| Field          | Type         | Null | Key | Default | Extra |'),
('+----------------+--------------+------+-----+---------+-------+'),
('| FeedbackID     | varchar(5)   | NO   | PRI | NULL    |       |'),
('| student_id     | varchar(5)   | NO   | MUL | NULL    |       |'),
('| Date           | date         | NO   |     | NULL    |       |'),
('| InstructorName | varchar(20)  | NO   |     | NULL    |       |'),
('| Feedback       | varchar(100) | NO   |     | NULL    |       |'),
('+----------------+--------------+------+-----+---------+-------+'),
('5 rows in set (0.005 sec)'),
('mysql> ');