CREATE TABLE Sheet1(Column_1 VARCHAR(10));
INSERT INTO Sheet1 (Column_1) VALUES 
('/* Lab 2: '),
('Database Schema: Consider a simple database with one tables: BankAccount BankAccount'),
('Table: ● Columns: account_id (Primary Key), account_holder_name, account_balance'),
('Task 1: Insert Data Write an SQL INSERT statement to insert data into the BankAccount table'),
('Task 2: Retrieving Data Write an SQL SELECT statement to retrieve the account_holder_name and account_balance of all account holders from the BankAccount table. '),
('Task 3: Filtering Data Write an SQL SELECT statement to retrieve the account_holder_name and account_balance where the account_balance is more than 30,000.'),
('Task 4: Updating Data Write an SQL UPDATE statement to change the account_balance of the account holder whose ID is 101. */'),
('mysql> create database Bank;'),
('Query OK, 1 row affected (0.007 sec)'),
('mysql> use Bank;'),
('Database changed'),
('#Table: ● Columns: account_id (Primary Key), account_holder_name, account_balance'),
('mysql> create table BankAccount (account_id varchar(5) not null primary key, account_holder_name varchar(20) not null, account_balance int not null);'),
('Query OK, 0 rows affected (0.036 sec)'),
('mysql> desc BankAccount;'),
('+---------------------+-------------+------+-----+---------+-------+'),
('| Field               | Type        | Null | Key | Default | Extra |'),
('+---------------------+-------------+------+-----+---------+-------+'),
('| account_id          | varchar(5)  | NO   | PRI | NULL    |       |'),
('| account_holder_name | varchar(20) | NO   |     | NULL    |       |'),
('| account_balance     | int         | NO   |     | NULL    |       |'),
('+---------------------+-------------+------+-----+---------+-------+'),
('3 rows in set (0.013 sec)'),
('#Task 1: Insert Data Write an SQL INSERT statement to insert data into the BankAccount table'),
('mysql> insert into BankAccount values ('101','Mannan',30000),('102','Ayesha', 32032),('103','Ariba',20000),('104','Faisal', 8739),('105','Khan',43872);'),
('Query OK, 5 rows affected (0.011 sec)'),
('Records: 5  Duplicates: 0  Warnings: 0'),
('#Task 2: Retrieving Data Write an SQL SELECT statement to retrieve the account_holder_name and account_balance of all account holders from the BankAccount table. '),
('mysql> select account_holder_name, account_balance from BankAccount;'),
('+---------------------+-----------------+'),
('| account_holder_name | account_balance |'),
('+---------------------+-----------------+'),
('| Mannan              |           30000 |'),
('| Ayesha              |           32032 |'),
('| Ariba               |           20000 |'),
('| Faisal              |            8739 |'),
('| Khan                |           43872 |'),
('+---------------------+-----------------+'),
('5 rows in set (0.002 sec)'),
('Task 3: Filtering Data Write an SQL SELECT statement to retrieve the account_holder_name and account_balance where the account_balance is more than 30,000.'),
('mysql> select account_holder_name, account_balance from BankAccount where account_balance>30000;'),
('+---------------------+-----------------+'),
('| account_holder_name | account_balance |'),
('+---------------------+-----------------+'),
('| Ayesha              |           32032 |'),
('| Khan                |           43872 |'),
('+---------------------+-----------------+'),
('2 rows in set (0.002 sec)'),
('Task 4: Updating Data Write an SQL UPDATE statement to change the account_balance of the account holder whose ID is 101. */'),
('mysql> update BankAccount set account_balance = 20000 where account_id = '101';'),
('Query OK, 1 row affected (0.020 sec)'),
('Rows matched: 1  Changed: 1  Warnings: 0'),
('mysql> select * from BankAccount;'),
('+------------+---------------------+-----------------+'),
('| account_id | account_holder_name | account_balance |'),
('+------------+---------------------+-----------------+'),
('| 101        | Mannan              |           20000 |'),
('| 102        | Ayesha              |           32032 |'),
('| 103        | Ariba               |           20000 |'),
('| 104        | Faisal              |            8739 |'),
('| 105        | Khan                |           43872 |'),
('+------------+---------------------+-----------------+'),
('5 rows in set (0.000 sec)');