CREATE TABLE Sheet1(Column_1 VARCHAR(10));
INSERT INTO Sheet1 (Column_1) VALUES 
('mysql> /*Create database Studentmanagementsystem contain  "Student" table with the following a columns:StudentId,FirstName,lastName'),
('   /*>  and "Course" table with the following a columns: CourseId,CourseName '),
('   /*> and Enrollment table with the following a columns:EnrollmentID,StudentID(Foreign key),CourseID(Foreign Key).'),
('   /*> You want to use inner join to generate a list of all possible student-course combinations. */'),
('    -> '),
('    -> ;'),
('Query OK, 0 rows affected (0.023 sec)'),
('mysql> drop database Studentmanagementsystem;'),
('Query OK, 3 rows affected (0.128 sec)'),
('mysql> create database Studentmanagementsystem;'),
('Query OK, 1 row affected (0.003 sec)'),
('mysql> use Studentmanagementsystem;'),
('Database changed'),
('mysql> create table Student(StudentId varchar(5) not null primary key, FirstName varchar(10) not null, lastName varchar(10) not null);'),
('Query OK, 0 rows affected (0.030 sec)'),
('mysql> desc Student;'),
('+-----------+-------------+------+-----+---------+-------+'),
('| Field     | Type        | Null | Key | Default | Extra |'),
('+-----------+-------------+------+-----+---------+-------+'),
('| StudentId | varchar(5)  | NO   | PRI | NULL    |       |'),
('| FirstName | varchar(10) | NO   |     | NULL    |       |'),
('| lastName  | varchar(10) | NO   |     | NULL    |       |'),
('+-----------+-------------+------+-----+---------+-------+'),
('3 rows in set (0.030 sec)'),
('mysql> insert into Student values('S101','Abdul','Ansari'),('S102','Khan','Ayesha'),('S103','Salman','Khan'),('S104','Tim','David'),('S105','Josh','Butler');'),
('Query OK, 5 rows affected (0.008 sec)'),
('Records: 5  Duplicates: 0  Warnings: 0'),
('mysql> select * from Student;'),
('+-----------+-----------+----------+'),
('| StudentId | FirstName | lastName |'),
('+-----------+-----------+----------+'),
('| S101      | Abdul     | Ansari   |'),
('| S102      | Khan      | Ayesha   |'),
('| S103      | Salman    | Khan     |'),
('| S104      | Tim       | David    |'),
('| S105      | Josh      | Butler   |'),
('+-----------+-----------+----------+'),
('5 rows in set (0.001 sec)'),
('mysql> create table Course(CourseId varchar(5) not null primary key, CourseName varchar(20) not null);'),
('Query OK, 0 rows affected (0.018 sec)'),
('mysql> desc Course;'),
('+------------+-------------+------+-----+---------+-------+'),
('| Field      | Type        | Null | Key | Default | Extra |'),
('+------------+-------------+------+-----+---------+-------+'),
('| CourseId   | varchar(5)  | NO   | PRI | NULL    |       |'),
('| CourseName | varchar(20) | NO   |     | NULL    |       |'),
('+------------+-------------+------+-----+---------+-------+'),
('2 rows in set (0.005 sec)'),
('mysql> insert into Course value('C1','Python'),('C2','Data Science'),('C3','Web Development'),('C4','Finance'),('C5','BMS');'),
('Query OK, 5 rows affected (0.006 sec)'),
('Records: 5  Duplicates: 0  Warnings: 0'),
('mysql> select * from Course;'),
('+----------+-----------------+'),
('| CourseId | CourseName      |'),
('+----------+-----------------+'),
('| C1       | Python          |'),
('| C2       | Data Science    |'),
('| C3       | Web Development |'),
('| C4       | Finance         |'),
('| C5       | BMS             |'),
('+----------+-----------------+'),
('5 rows in set (0.000 sec)'),
('mysql> create table Enrollment(EnrollmentId varchar(5) not null primary key, StudentId varchar(5) not null, CourseId varchar(5) not null, foreign key(StudentId) references Student(StudentId), foreign key(CourseId) references Course(CourseId));'),
('Query OK, 0 rows affected (0.028 sec)'),
('mysql> desc Enrollment;'),
('+--------------+------------+------+-----+---------+-------+'),
('| Field        | Type       | Null | Key | Default | Extra |'),
('+--------------+------------+------+-----+---------+-------+'),
('| EnrollmentId | varchar(5) | NO   | PRI | NULL    |       |'),
('| StudentId    | varchar(5) | NO   | MUL | NULL    |       |'),
('| CourseId     | varchar(5) | NO   | MUL | NULL    |       |'),
('+--------------+------------+------+-----+---------+-------+'),
('3 rows in set (0.007 sec)'),
('mysql> insert into Enrollment value('E1','S101','C1'),('E2','S102','C2'),('E3','S103','C3'),('E4','S104','C4'),('E5','S105','C5');'),
('Query OK, 5 rows affected (0.012 sec)'),
('Records: 5  Duplicates: 0  Warnings: 0'),
('mysql> select * from Enrollment;'),
('+--------------+-----------+----------+'),
('| EnrollmentId | StudentId | CourseId |'),
('+--------------+-----------+----------+'),
('| E1           | S101      | C1       |'),
('| E2           | S102      | C2       |'),
('| E3           | S103      | C3       |'),
('| E4           | S104      | C4       |'),
('| E5           | S105      | C5       |'),
('+--------------+-----------+----------+'),
('5 rows in set (0.001 sec)'),
('mysql> select Student.StudentId,Student.FirstName,Student.lastName,Course.CourseName,Course.CourseId from Enrollment inner join Student on Enrollment.StudentId=Student.StudentId inner join Course on Enrollment.CourseId=Course.CourseId;'),
('+-----------+-----------+----------+-----------------+----------+'),
('| StudentId | FirstName | lastName | CourseName      | CourseId |'),
('+-----------+-----------+----------+-----------------+----------+'),
('| S101      | Abdul     | Ansari   | Python          | C1       |'),
('| S102      | Khan      | Ayesha   | Data Science    | C2       |'),
('| S103      | Salman    | Khan     | Web Development | C3       |'),
('| S104      | Tim       | David    | Finance         | C4       |'),
('| S105      | Josh      | Butler   | BMS             | C5       |'),
('+-----------+-----------+----------+-----------------+----------+'),
('5 rows in set (0.023 sec)'),
('mysql> ');